#/*********************************************************************
# Copyright (c) Intel Corporation 2020
# SPDX-License-Identifier: Apache-2.0
#**********************************************************************/
{{- if .Values.console.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: console
  name: console
spec:
  ports:
  - port: 4433
    name: cira
    protocol: TCP
    targetPort: 4433
  - port: 3000
    name: webapi
    protocol: TCP
    targetPort: 3000
  selector:
    app: console
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: console
spec:
  replicas: {{ .Values.console.replicaCount }}
  selector:
    matchLabels:
      app: console
  template:
    metadata:
      labels:
        app: console
    spec:
      imagePullSecrets:
        - name: registrycredentials
      containers:
        - name: console
          image: {{ .Values.images.console }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
            periodSeconds: 12
            timeoutSeconds: 12
            failureThreshold: 3
          env:
            - name: "APP_COMMON_NAME"
              value: "{{ .Values.console.commonName }}"
            - name: "APP_ENCRYPTION_KEY"
              valueFrom:
                secretKeyRef:
                  name: console
                  key: appEncryptionKey
            - name: "APP_DISABLE_CIRA"
              value: "false"
            - name: "HTTP_PORT"
              value: "3000"
            - name: "HTTP_HOST"
              value: "0.0.0.0"
            - name: "HTTP_TLS_ENABLED"
              value: "false"
            - name: "LOG_LEVEL"
              value: "{{ .Values.console.logLevel }}"
            - name: "DB_PROVIDER"
              value: "postgres"
            - name: "DB_URL"
              valueFrom:
                secretKeyRef:
                  name: console
                  key: connectionString
            - name: "SECRETS_ADDR"
              value: "http://{{ .Release.Name }}-vault:8200"
            - name: "SECRETS_PATH"
              value: 'kv/data/'
            - name: "SECRETS_TOKEN"
              valueFrom:
                secretKeyRef:
                  name: vault
                  key: vaultKey
            - name: "AUTH_JWT_KEY"
              valueFrom:
                secretKeyRef:
                  name: device-mgmt-toolkit-admin-jwt
                  key: secret
            - name: "AUTH_ISSUER"
              valueFrom:
                secretKeyRef:
                  name: device-mgmt-toolkit-admin-jwt
                  key: key
            - name: "AUTH_ADMIN_USERNAME"
              valueFrom:
                secretKeyRef:
                  name: consoleweb
                  key: user
            - name: "AUTH_ADMIN_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: consoleweb
                  key: password
          ports:
            - containerPort: 3000
              name: webapi
            - containerPort: 4433
              name: cira
{{- end }}
